package com.pocspace.customer_greeting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String maritalStatus;
	private java.lang.String gender;

	public Customer() {
	}

	public java.lang.String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(java.lang.String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public Customer(java.lang.String maritalStatus, java.lang.String gender) {
		this.maritalStatus = maritalStatus;
		this.gender = gender;
	}

}