package com.pocspace.customer_greeting;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GreetingResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String salutation;

	public GreetingResponse() {
	}

	public java.lang.String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(java.lang.String salutation) {
		this.salutation = salutation;
	}

	public GreetingResponse(java.lang.String salutation) {
		this.salutation = salutation;
	}

}